//go:build parity

package parity

import (
	"os"
	"strings"
	"testing"
)

// reportLockCells records that the test running t compared n more cells. A cell
// is one comparison of hot against cold: a case, a query, a row set.
//
// The Parity Tests job (scripts/ci/parity_ratchet.py --lock-cells) holds every
// lock test listed in lock_cells.txt to a minimum number of reported cells, so a
// lock that is skipped, emptied, made to return early, constrained away by a
// build tag or file name, or silenced by a TestMain reports too few cells and
// fails the job, however the test file was edited. The floor only grows: a
// parity fix that adds cells passes freely; lowering it needs the owner.
//
// This file must not call t.Helper: go test then prefixes the line with this
// file's name and line, and the ratchet accepts a lock-cells line only from exactly
// that file:line, for the test test2json attributes it to, carrying the run's
// nonce (PARITY_LOCK_NONCE, generated by the workflow step that runs the suite).
// The file is a gate file, and so is every file a lock test calls into.
//
// The nonce is NOT a security control: code in the test process can read it from the
// environment and print a forged line, so it only guards against an accidental stale
// or copied line. What stops forged cells is the owner gate on lock packages: any edit
// of an existing file of this package (or its runtime config), and any new file that
// declares a package-level var, init() or TestMain, needs the owner (see
// tests/conformance/README.md).
func reportLockCells(t *testing.T, n int) {
	root, _, _ := strings.Cut(t.Name(), "/")
	nonce := os.Getenv("PARITY_LOCK_NONCE")
	if nonce == "" {
		nonce = "-" // a local run: the ratchet is not involved
	}
	t.Logf("lock-cells %s %s %d", nonce, root, n)
}
