FROM golang:1.26.2-alpine3.22 AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /datagen ./cmd/datagen

FROM gcr.io/distroless/static-debian12:nonroot
COPY --from=builder /datagen /usr/local/bin/datagen
USER nonroot
ENTRYPOINT ["/usr/local/bin/datagen"]
