{{- if and .Values.select.enabled .Values.select.horizontalPodAutoscaler.enabled }}
{{- $fullname := include "victoria-lakehouse.fullname" . }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $fullname }}-select
  labels:
    {{- include "victoria-lakehouse.componentLabels" (dict "context" . "component" "select") | nindent 4 }}
  {{- with .Values.global.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    {{- if .Values.select.persistence.enabled }}
    kind: StatefulSet
    {{- else }}
    kind: Deployment
    {{- end }}
    name: {{ $fullname }}-select
  minReplicas: {{ .Values.select.horizontalPodAutoscaler.minReplicas }}
  maxReplicas: {{ .Values.select.horizontalPodAutoscaler.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.select.horizontalPodAutoscaler.targetCPUUtilizationPercentage }}
{{- end }}
{{- if and .Values.insertComponent.enabled .Values.insertComponent.horizontalPodAutoscaler.enabled }}
{{- $fullname := include "victoria-lakehouse.fullname" . }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $fullname }}-insert
  labels:
    {{- include "victoria-lakehouse.componentLabels" (dict "context" . "component" "insert") | nindent 4 }}
  {{- with .Values.global.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    {{- if .Values.insertComponent.persistence.enabled }}
    kind: StatefulSet
    {{- else }}
    kind: Deployment
    {{- end }}
    name: {{ $fullname }}-insert
  minReplicas: {{ .Values.insertComponent.horizontalPodAutoscaler.minReplicas }}
  maxReplicas: {{ .Values.insertComponent.horizontalPodAutoscaler.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.insertComponent.horizontalPodAutoscaler.targetCPUUtilizationPercentage }}
{{- end }}
