{{- if and .Values.select.enabled .Values.select.headlessService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "victoria-lakehouse.fullname" . }}-select-headless
  labels:
    {{- include "victoria-lakehouse.componentLabels" (dict "root" . "component" "select") | nindent 4 }}
  {{- with .Values.select.headlessService.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http
      port: {{ include "victoria-lakehouse.servicePort" . }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "victoria-lakehouse.componentSelectorLabels" (dict "root" . "component" "select") | nindent 4 }}
{{- end }}
