{{- $port := 9428 }}
{{- if eq .Values.mode "traces" }}
{{- $port = 10428 }}
{{- end }}
{{- if .Values.service.port }}
{{- $port = .Values.service.port }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "victoria-lakehouse.fullname" . }}
  labels:
    {{- include "victoria-lakehouse.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ $port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "victoria-lakehouse.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "victoria-lakehouse.fullname" . }}-headless
  labels:
    {{- include "victoria-lakehouse.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ $port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "victoria-lakehouse.selectorLabels" . | nindent 4 }}
