{{- range $name, $spec := dict "select" $.Values.select "insert" $.Values.insertComponent "vmauth" $.Values.vmauth }}
{{- if and $spec.enabled (dig "serviceMonitor" "enabled" false $spec) }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "victoria-lakehouse.fullname" $ }}-{{ $name }}
  labels:
    {{- include "victoria-lakehouse.componentLabels" (dict "root" $ "component" $name) | nindent 4 }}
    {{- with $spec.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "victoria-lakehouse.componentSelectorLabels" (dict "root" $ "component" $name) | nindent 6 }}
  endpoints:
    - port: http
      interval: {{ $spec.serviceMonitor.interval }}
{{- end }}
{{- end }}
