{{- if and .Values.select.enabled .Values.select.serviceMonitor.enabled }}
{{- $port := include "victoria-lakehouse.port" (dict "context" . "servicePort" .Values.select.service.port) }}
{{- $fullname := include "victoria-lakehouse.fullname" . }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ $fullname }}-select
  labels:
    {{- include "victoria-lakehouse.componentLabels" (dict "context" . "component" "select") | nindent 4 }}
    {{- with .Values.select.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.global.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "victoria-lakehouse.componentSelectorLabels" (dict "context" . "component" "select") | nindent 6 }}
  endpoints:
    - port: http
      interval: {{ .Values.select.serviceMonitor.interval }}
      path: /metrics
{{- end }}
{{- if and .Values.insertComponent.enabled .Values.insertComponent.serviceMonitor.enabled }}
{{- $port := include "victoria-lakehouse.port" (dict "context" . "servicePort" .Values.insertComponent.service.port) }}
{{- $fullname := include "victoria-lakehouse.fullname" . }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ $fullname }}-insert
  labels:
    {{- include "victoria-lakehouse.componentLabels" (dict "context" . "component" "insert") | nindent 4 }}
    {{- with .Values.insertComponent.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.global.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "victoria-lakehouse.componentSelectorLabels" (dict "context" . "component" "insert") | nindent 6 }}
  endpoints:
    - port: http
      interval: {{ .Values.insertComponent.serviceMonitor.interval }}
      path: /metrics
{{- end }}
{{- if and .Values.vmauth.enabled .Values.vmauth.serviceMonitor.enabled }}
{{- $fullname := include "victoria-lakehouse.fullname" . }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ $fullname }}-vmauth
  labels:
    {{- include "victoria-lakehouse.componentLabels" (dict "context" . "component" "vmauth") | nindent 4 }}
    {{- with .Values.vmauth.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.global.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "victoria-lakehouse.componentSelectorLabels" (dict "context" . "component" "vmauth") | nindent 6 }}
  endpoints:
    - port: http
      interval: {{ .Values.vmauth.serviceMonitor.interval }}
      path: /metrics
{{- end }}
