{{- if .Values.vmauth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "victoria-lakehouse.fullname" . }}-vmauth
  labels:
    {{- include "victoria-lakehouse.genericComponentLabels" (dict "root" . "component" "vmauth") | nindent 4 }}
type: Opaque
stringData:
  auth.yml: |
    {{- if .Values.vmauth.config }}
    {{ .Values.vmauth.config | nindent 4 }}
    {{- else }}
    unauthorized_user:
      url_map:
        {{- if .Values.logs.enabled }}
        {{- if .Values.logs.insert.enabled }}
        - src_paths:
            - "/insert/.*"
            - "/internal/insert"
          url_prefix:
            - "http://{{ include "victoria-lakehouse.fullname" . }}-logs-insert:9428/"
          discover_backend_ips: true
        {{- end }}
        {{- if .Values.logs.select.enabled }}
        - src_paths:
            - "/select/logsql/.*"
            - "/delete/logsql/.*"
          url_prefix:
            - "http://{{ include "victoria-lakehouse.fullname" . }}-logs-select:9428/"
          discover_backend_ips: true
        {{- end }}
        {{- end }}
        {{- if .Values.traces.enabled }}
        {{- if .Values.traces.insert.enabled }}
        - src_paths:
            - "/insert/.*"
          headers:
            - "X-Lakehouse-Signal: traces"
          url_prefix:
            - "http://{{ include "victoria-lakehouse.fullname" . }}-traces-insert:10428/"
          discover_backend_ips: true
        {{- end }}
        {{- if .Values.traces.select.enabled }}
        - src_paths:
            - "/select/jaeger/.*"
            - "/tempo/.*"
            - "/select/logsql/.*"
          headers:
            - "X-Lakehouse-Signal: traces"
          url_prefix:
            - "http://{{ include "victoria-lakehouse.fullname" . }}-traces-select:10428/"
          discover_backend_ips: true
        {{- end }}
        {{- end }}
        {{- if and .Values.logs.enabled .Values.logs.select.enabled }}
        - src_paths:
            - "/.*"
          url_prefix:
            - "http://{{ include "victoria-lakehouse.fullname" . }}-logs-select:9428/"
          discover_backend_ips: true
        {{- end }}
    {{- end }}
{{- end }}
