{{- if .Values.vmauth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "victoria-lakehouse.fullname" . }}-vmauth
  labels:
    {{- include "victoria-lakehouse.componentLabels" (dict "root" . "component" "vmauth") | nindent 4 }}
type: Opaque
stringData:
  auth.yml: |
    {{- if .Values.vmauth.config }}
    {{ .Values.vmauth.config | nindent 4 }}
    {{- else }}
    unauthorized_user:
      url_map:
        - src_paths:
            - "/insert/.*"
            - "/internal/insert"
          url_prefix:
            - "http://{{ include "victoria-lakehouse.fullname" . }}-insert:{{ include "victoria-lakehouse.servicePort" . }}/"
          discover_backend_ips: true
        - src_paths:
            - "/.*"
          url_prefix:
            - "http://{{ include "victoria-lakehouse.fullname" . }}-select:{{ include "victoria-lakehouse.servicePort" . }}/"
          discover_backend_ips: true
    {{- end }}
{{- end }}
