package inventory

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"gopkg.in/yaml.v3"
)

type Dirs struct {
	VL, VT               string
	VLVersion, VTVersion string
}

var mkVLRe = regexp.MustCompile(`(?m)^VL_VERSION_LOGS\s*:=\s*(\S+)`)
var mkVTRe = regexp.MustCompile(`(?m)^VT_VERSION\s*:=\s*(\S+)`)

// DefaultDirs points at the vendored trees the Makefile clones and reads the
// pinned versions from it (single source of truth for the pins).
func DefaultDirs(repoRoot string) Dirs {
	d := Dirs{VL: filepath.Join(repoRoot, "deps", "VictoriaLogs"), VT: filepath.Join(repoRoot, "lakehouse-traces", "deps", "VictoriaTraces")}
	if mk, err := os.ReadFile(filepath.Join(repoRoot, "Makefile")); err == nil {
		if m := mkVLRe.FindSubmatch(mk); m != nil {
			d.VLVersion = string(m[1])
		}
		if m := mkVTRe.FindSubmatch(mk); m != nil {
			d.VTVersion = string(m[1])
		}
	}
	return d
}

// RepoRoot walks up from the working directory to the lakehouse go.mod.
func RepoRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if data, err := os.ReadFile(filepath.Join(dir, "go.mod")); err == nil && strings.Contains(string(data), "module github.com/ReliablyObserve/victoria-lakehouse") {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("lakehouse go.mod not found above %s", dir)
		}
		dir = parent
	}
}

// Extract runs all six extractors in order, dedups by Key, sets versions from Dirs.
func Extract(d Dirs) (*Inventory, error) {
	inv := &Inventory{VLVersion: d.VLVersion, VTVersion: d.VTVersion}
	steps := []func() ([]Item, error){
		func() ([]Item, error) { return ExtractVLRoutes(d.VL) },
		func() ([]Item, error) { return ExtractVTRoutes(d.VT) },
		func() ([]Item, error) { return ExtractEngine(d.VL) },
		func() ([]Item, error) { return ExtractTraceQL(d.VT) },
		func() ([]Item, error) { return ExtractFlags(d.VL, VLFlagPackages, LinkedIntoLH) },
		func() ([]Item, error) { return ExtractFlags(d.VT, VTFlagPackages, LinkedIntoLH) },
	}
	seen := map[string]bool{}
	for _, s := range steps {
		items, err := s()
		if err != nil {
			return nil, err
		}
		for _, it := range items {
			k := inv.Key(it)
			if !seen[k] {
				seen[k] = true
				inv.Items = append(inv.Items, it)
			}
		}
	}
	return inv, nil
}

// Write writes the inventory to a YAML file with a GENERATED header comment.
func (inv *Inventory) Write(path string) error {
	data, err := yaml.Marshal(inv)
	if err != nil {
		return err
	}
	header := "# GENERATED by `make conformance-gen` from the vendored upstream sources — do not edit.\n"
	return os.WriteFile(path, append([]byte(header), data...), 0o644)
}

// Read reads an inventory from a YAML file.
func Read(path string) (*Inventory, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var inv Inventory
	if err := yaml.Unmarshal(data, &inv); err != nil {
		return nil, fmt.Errorf("%s: %w", path, err)
	}
	return &inv, nil
}
