package inventory

import (
	"os"
	"path/filepath"
	"reflect"
	"regexp"
	"sort"
	"strings"
	"testing"
)

func TestExtract_FixtureRoundTrip(t *testing.T) {
	inv, err := Extract(Dirs{VL: "testdata/mini-vl", VT: "testdata/mini-vt", VLVersion: "x", VTVersion: "y"})
	if err != nil {
		t.Fatal(err)
	}
	if !has(inv.Items, "route", "/select/logsql/query") || !has(inv.Items, "pipe", "coalesce") || !has(inv.Items, "traceql", "rate") || !has(inv.Items, "flag", "search.maxQueueDuration") {
		t.Fatalf("inventory incomplete: %+v", inv.Items)
	}
	p := filepath.Join(t.TempDir(), "inv.yaml")
	if err := inv.Write(p); err != nil {
		t.Fatal(err)
	}
	back, err := Read(p)
	if err != nil || len(back.Items) != len(inv.Items) || back.VLVersion != "x" {
		t.Fatalf("round trip: %v %+v", err, back)
	}
}

// TestInventory_BytesMatchesWrite proves Bytes() renders exactly what Write
// persists (header + YAML), so confgen can compare in memory instead of
// round-tripping through a temp file.
func TestInventory_BytesMatchesWrite(t *testing.T) {
	inv, err := Extract(Dirs{VL: "testdata/mini-vl", VT: "testdata/mini-vt", VLVersion: "x", VTVersion: "y"})
	if err != nil {
		t.Fatal(err)
	}
	want, err := inv.Bytes()
	if err != nil {
		t.Fatal(err)
	}
	p := filepath.Join(t.TempDir(), "inv.yaml")
	if err := inv.Write(p); err != nil {
		t.Fatal(err)
	}
	got, err := os.ReadFile(p)
	if err != nil {
		t.Fatal(err)
	}
	if string(got) != string(want) {
		t.Fatalf("Bytes() does not match what Write persisted:\nBytes: %s\nWrite: %s", want, got)
	}
	if !strings.HasPrefix(string(want), "# GENERATED by") {
		t.Fatalf("Bytes() missing GENERATED header: %s", want)
	}
}

// Real vendored trees: required in CI (CONFORMANCE_REQUIRE_DEPS=1), optional locally.
func TestExtract_RealDeps(t *testing.T) {
	root, err := RepoRoot()
	if err != nil {
		t.Fatal(err)
	}
	d := DefaultDirs(root)
	for _, dir := range []string{d.VL, d.VT} {
		if _, err := os.Stat(dir); err != nil {
			if os.Getenv("CONFORMANCE_REQUIRE_DEPS") == "1" {
				t.Fatalf("deps missing (%s): run make deps-logs deps-traces deps-vt", dir)
			}
			t.Skip("vendored deps not present locally")
		}
	}
	inv, err := Extract(d)
	if err != nil {
		t.Fatal(err)
	}
	for _, w := range [][2]string{{"route", "/select/logsql/query"}, {"route", "/select/jaeger/api/traces/"}, {"route", "/select/tempo/api/search"},
		{"pipe", "stats"}, {"filter", "range"}, {"stats", "quantile"}, {"traceql", "histogram_over_time"}, {"flag", "search.maxConcurrentRequests"}} {
		if !has(inv.Items, w[0], w[1]) {
			t.Fatalf("real deps: missing %v", w)
		}
	}
	if d.VLVersion == "" || d.VTVersion == "" {
		t.Fatalf("versions not read from Makefile: %+v", d)
	}

	// TraceQL metric-pipe functions: assert the exact expected set (not
	// just a few sampled names) against the real vendored pipe_metrics.go,
	// so a regression in the isKeyword-derivation (extract_engine.go) that
	// drops or spuriously adds a function is caught here even if the
	// hand-written mini-vt fixture test still passes.
	var traceqlNames []string
	for _, it := range inv.Items {
		if it.Kind == "traceql" {
			traceqlNames = append(traceqlNames, it.Name)
		}
	}
	sort.Strings(traceqlNames)
	wantTraceQL := []string{
		"avg_over_time", "compare", "count_over_time", "histogram_over_time",
		"max_over_time", "min_over_time", "quantile_over_time", "rate", "sum_over_time",
	}
	if !reflect.DeepEqual(traceqlNames, wantTraceQL) {
		t.Fatalf("real deps: TraceQL function set = %v, want exactly %v", traceqlNames, wantTraceQL)
	}

	// Log counts per kind for transparency
	counts := make(map[string]int)
	for _, it := range inv.Items {
		counts[it.Kind]++
	}
	t.Logf("real deps inventory: routes=%d pipes=%d filters=%d stats=%d traceql=%d flags=%d total=%d",
		counts["route"], counts["pipe"], counts["filter"], counts["stats"], counts["traceql"], counts["flag"], len(inv.Items))
}

// vtVLRequireRe pulls the VictoriaLogs pseudo-version out of VictoriaTraces'
// own go.mod require block, e.g.
//
//	github.com/VictoriaMetrics/VictoriaLogs v1.121.1-0.20260617051904-6ae2da3c11f3 // v1.51.0
var vtVLRequireRe = regexp.MustCompile(`(?m)^\s*github\.com/VictoriaMetrics/VictoriaLogs\s+(\S+)`)

// TestVLCommitTracesPinIsDerivedFromVT pins the derivation rule for the second
// VictoriaLogs pin: VL_COMMIT_TRACES is never chosen, it is read off
// VictoriaTraces' own go.mod at VT_VERSION. The traces binary links VT against
// the exact VictoriaLogs commit VT was built and tested with, so lifting the
// pin to VL_VERSION_LOGS "because it compiles" is a silent compatibility
// change. This test fails the moment the Makefile pin stops matching the
// vendored VT tree.
func TestVLCommitTracesPinIsDerivedFromVT(t *testing.T) {
	root, err := RepoRoot()
	if err != nil {
		t.Fatal(err)
	}
	d := DefaultDirs(root)
	if d.VLCommitTraces == "" {
		t.Fatal("VL_COMMIT_TRACES not found in the Makefile")
	}
	vtGoMod := filepath.Join(root, "lakehouse-traces", "deps", "VictoriaTraces", "go.mod")
	data, err := os.ReadFile(vtGoMod)
	if err != nil {
		if os.Getenv("CONFORMANCE_REQUIRE_DEPS") == "1" {
			t.Fatalf("deps missing (%s): run make deps-vt", vtGoMod)
		}
		t.Skip("vendored deps not present locally")
	}
	m := vtVLRequireRe.FindSubmatch(data)
	if m == nil {
		t.Fatalf("no VictoriaLogs require line in %s", vtGoMod)
	}
	vtPin := string(m[1])
	// The Makefile pin is the short commit; VT's pseudo-version ends in the
	// 12-char commit prefix (vX.Y.Z-0.<timestamp>-<commit>).
	idx := strings.LastIndex(vtPin, "-")
	if idx < 0 {
		t.Fatalf("VictoriaTraces pins VictoriaLogs at %q, which is not a pseudo-version — the derivation rule needs revisiting", vtPin)
	}
	wantCommit := vtPin[idx+1:]
	if d.VLCommitTraces != wantCommit {
		t.Fatalf("VL_COMMIT_TRACES = %s, but VictoriaTraces %s pins VictoriaLogs at %s (commit %s).\n"+
			"The traces-side VL pin is derived from VT's go.mod, never chosen — see the Makefile comment.",
			d.VLCommitTraces, d.VTVersion, vtPin, wantCommit)
	}
}

// TestVLSurface_LogsPinSupersetOfTracesPin guards the claim in DefaultDirs'
// doc comment: DefaultDirs extracts the shared VictoriaLogs surface (routes,
// engine tables, flags) from the logs-pin copy (deps/VictoriaLogs) only, even
// though the traces module vendors its own copy at VL_COMMIT_TRACES.
//
// The two pins are deliberately allowed to differ — the logs binary tracks the
// newest VictoriaLogs release, the traces binary follows whatever VictoriaTraces
// pins — so item-for-item equality is the wrong assertion. What must hold is
// containment: everything the traces-pin copy exposes is also in the logs-pin
// copy, so extracting the logs pin alone never *misses* a surface. The reverse
// direction (logs-only items, i.e. what the newer VictoriaLogs added) is
// expected and reported, not failed; those items are covered by registry rows
// carrying the version they appeared in.
//
// A failure here means the newer VictoriaLogs *removed* something the traces
// binary still serves: the inventory would then silently under-report the
// traces surface and DefaultDirs must start extracting both copies.
func TestVLSurface_LogsPinSupersetOfTracesPin(t *testing.T) {
	root, err := RepoRoot()
	if err != nil {
		t.Fatal(err)
	}
	d := DefaultDirs(root)
	tracesVL := filepath.Join(root, "lakehouse-traces", "deps", "VictoriaLogs")
	for _, dir := range []string{d.VL, tracesVL} {
		if _, err := os.Stat(dir); err != nil {
			if os.Getenv("CONFORMANCE_REQUIRE_DEPS") == "1" {
				t.Fatalf("deps missing (%s): run make deps-logs deps-traces", dir)
			}
			t.Skip("vendored deps not present locally")
		}
	}

	extractors := []struct {
		what string
		fn   func(dir string) ([]Item, error)
	}{
		{"routes", ExtractVLRoutes},
		{"engine tables", ExtractEngine},
		{"flags", func(dir string) ([]Item, error) {
			return ExtractFlags(dir, VLFlagPackages, LinkedIntoLH, "vl")
		}},
	}
	for _, e := range extractors {
		t.Run(e.what, func(t *testing.T) {
			logsItems, err := e.fn(d.VL)
			if err != nil {
				t.Fatal(err)
			}
			tracesItems, err := e.fn(tracesVL)
			if err != nil {
				t.Fatal(err)
			}
			if len(logsItems) == 0 || len(tracesItems) == 0 {
				t.Fatalf("extraction produced no %s (logs=%d traces=%d) — the containment check would pass vacuously",
					e.what, len(logsItems), len(tracesItems))
			}
			logsSet := make(map[Item]bool, len(logsItems))
			for _, it := range logsItems {
				logsSet[it] = true
			}
			var missing []string
			for _, it := range tracesItems {
				if !logsSet[it] {
					missing = append(missing, it.Kind+":"+it.Name)
				}
			}
			if len(missing) > 0 {
				t.Fatalf("VL %s present at the traces pin (%s) but absent at the logs pin (%s): %s\n"+
					"The logs pin must be a superset; otherwise the inventory under-reports the traces surface "+
					"and DefaultDirs must extract both copies.",
					e.what, d.VLCommitTraces, d.VLVersion, strings.Join(missing, ", "))
			}
			tracesSet := make(map[Item]bool, len(tracesItems))
			for _, it := range tracesItems {
				tracesSet[it] = true
			}
			var added []string
			for _, it := range logsItems {
				if !tracesSet[it] {
					added = append(added, it.Kind+":"+it.Name)
				}
			}
			sort.Strings(added)
			t.Logf("VL %s: traces pin %s ⊆ logs pin %s; logs-only (newer upstream): %d%s",
				e.what, d.VLCommitTraces, d.VLVersion, len(added), formatDelta(added))
		})
	}
}

// formatDelta renders the logs-only item list for the t.Logf above, capped so
// a large upstream jump doesn't bury the test output.
func formatDelta(added []string) string {
	if len(added) == 0 {
		return ""
	}
	const max = 20
	if len(added) > max {
		return " [" + strings.Join(added[:max], ", ") + ", …]"
	}
	return " [" + strings.Join(added, ", ") + "]"
}

// TestInventory_FullRoundTripEquality proves Write→Read reproduces the
// exact same Inventory struct, field for field (not just item count and one
// version field, which TestExtract_FixtureRoundTrip already checked) —
// including per-item Surface, Linked, and the VLCommitTraces pin.
func TestInventory_FullRoundTripEquality(t *testing.T) {
	inv, err := Extract(Dirs{VL: "testdata/mini-vl", VT: "testdata/mini-vt", VLVersion: "x", VTVersion: "y", VLCommitTraces: "deadbeef"})
	if err != nil {
		t.Fatal(err)
	}
	if len(inv.Items) == 0 {
		t.Fatal("fixture extraction produced no items — test would pass vacuously")
	}
	p := filepath.Join(t.TempDir(), "inv.yaml")
	if err := inv.Write(p); err != nil {
		t.Fatal(err)
	}
	back, err := Read(p)
	if err != nil {
		t.Fatal(err)
	}
	if !reflect.DeepEqual(inv, back) {
		t.Fatalf("round trip is not field-for-field equal:\nwant: %+v\ngot:  %+v", inv, back)
	}
}

// TestInventory_Write_ErrorOnBadPath proves Write surfaces the underlying
// os.WriteFile error (e.g. a parent directory that does not exist) instead
// of silently discarding it.
func TestInventory_Write_ErrorOnBadPath(t *testing.T) {
	inv := &Inventory{VLVersion: "x", VTVersion: "y"}
	err := inv.Write(filepath.Join(t.TempDir(), "no-such-dir", "inv.yaml"))
	if err == nil {
		t.Fatal("expected an error writing into a nonexistent directory")
	}
}

// TestInventory_Read_MissingFile proves Read surfaces the os.ReadFile error
// for a missing file rather than returning a zero-value Inventory silently.
func TestInventory_Read_MissingFile(t *testing.T) {
	_, err := Read(filepath.Join(t.TempDir(), "does-not-exist.yaml"))
	if err == nil {
		t.Fatal("expected an error reading a missing file")
	}
}

// TestInventory_Read_MalformedYAML proves Read wraps a YAML decode error
// with the file path (fmt.Errorf("%s: %w", path, err)), so the error
// message tells you which file failed to parse.
func TestInventory_Read_MalformedYAML(t *testing.T) {
	p := filepath.Join(t.TempDir(), "bad.yaml")
	if err := os.WriteFile(p, []byte("items: [this is not, valid: yaml: at all"), 0o644); err != nil {
		t.Fatal(err)
	}
	_, err := Read(p)
	if err == nil {
		t.Fatal("expected a YAML decode error")
	}
	if !strings.Contains(err.Error(), p) {
		t.Fatalf("expected the error to mention the file path %q, got: %v", p, err)
	}
}
