package inventory

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"

	"gopkg.in/yaml.v3"
)

type Dirs struct {
	VL, VT               string
	VLVersion, VTVersion string
	// VLCommitTraces is the VL_COMMIT_TRACES pin read from the Makefile: the
	// commit of the VictoriaLogs tree the traces module vendors its own copy
	// of (lakehouse-traces/deps/VictoriaLogs), independent of VLVersion.
	VLCommitTraces string
}

var mkVLRe = regexp.MustCompile(`(?m)^VL_VERSION_LOGS\s*:=\s*(\S+)`)
var mkVTRe = regexp.MustCompile(`(?m)^VT_VERSION\s*:=\s*(\S+)`)
var mkVLCommitTracesRe = regexp.MustCompile(`(?m)^VL_COMMIT_TRACES\s*:=\s*(\S+)`)

// moduleLineRe matches the lakehouse module's own module declaration line
// exactly, so it never matches the traces module's go.mod (which declares a
// different module in the same repo tree).
var moduleLineRe = regexp.MustCompile(`(?m)^module github\.com/ReliablyObserve/victoria-lakehouse$`)

// DefaultDirs points at the vendored trees the Makefile clones and reads the
// pinned versions from it (single source of truth for the pins).
//
// deps/VictoriaLogs (VL_VERSION_LOGS) is the VL basis for the logs surface.
// The traces module vendors its own separate copy of VictoriaLogs at
// lakehouse-traces/deps/VictoriaLogs, pinned to VL_COMMIT_TRACES — the commit
// VictoriaTraces itself requires, which legitimately lags VL_VERSION_LOGS.
// Only the logs-pin copy is extracted here; two guard tests back that
// shortcut: TestVLCommitTracesPinIsDerivedFromVT (the traces pin really is
// VT's own) and TestVLSurface_LogsPinSupersetOfTracesPin (the logs-pin
// surface contains everything the traces-pin copy exposes, so nothing is
// missed; the logs-only delta is newer upstream and is reported, not failed).
func DefaultDirs(repoRoot string) Dirs {
	d := Dirs{VL: filepath.Join(repoRoot, "deps", "VictoriaLogs"), VT: filepath.Join(repoRoot, "lakehouse-traces", "deps", "VictoriaTraces")}
	if mk, err := os.ReadFile(filepath.Join(repoRoot, "Makefile")); err == nil {
		if m := mkVLRe.FindSubmatch(mk); m != nil {
			d.VLVersion = string(m[1])
		}
		if m := mkVTRe.FindSubmatch(mk); m != nil {
			d.VTVersion = string(m[1])
		}
		if m := mkVLCommitTracesRe.FindSubmatch(mk); m != nil {
			d.VLCommitTraces = string(m[1])
		}
	}
	return d
}

// RepoRoot walks up from the working directory to the lakehouse go.mod. It
// matches the module declaration line exactly so it never matches the
// traces module's own go.mod (a different module further down the tree).
func RepoRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if data, err := os.ReadFile(filepath.Join(dir, "go.mod")); err == nil && moduleLineRe.Match(data) {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("lakehouse go.mod not found above %s", dir)
		}
		dir = parent
	}
}

// Extract runs all six extractors in order, dedups by Key, sets versions from Dirs.
func Extract(d Dirs) (*Inventory, error) {
	inv := &Inventory{VLVersion: d.VLVersion, VTVersion: d.VTVersion, VLCommitTraces: d.VLCommitTraces}
	steps := []func() ([]Item, error){
		func() ([]Item, error) { return ExtractVLRoutes(d.VL) },
		func() ([]Item, error) { return ExtractVTRoutes(d.VT) },
		func() ([]Item, error) { return ExtractEngine(d.VL) },
		func() ([]Item, error) { return ExtractTraceQL(d.VT) },
		func() ([]Item, error) { return ExtractFlags(d.VL, VLFlagPackages, LinkedIntoLH, "vl") },
		func() ([]Item, error) { return ExtractFlags(d.VT, VTFlagPackages, LinkedIntoLH, "vt") },
	}
	seen := map[string]bool{}
	for _, s := range steps {
		items, err := s()
		if err != nil {
			return nil, err
		}
		for _, it := range items {
			k := inv.Key(it)
			if !seen[k] {
				seen[k] = true
				inv.Items = append(inv.Items, it)
			}
		}
	}
	return inv, nil
}

// Bytes renders the inventory exactly as Write would persist it: the
// GENERATED header comment followed by the YAML encoding. Callers that only
// need to compare or inspect the rendered form (confgen's -check/-write)
// should use this instead of writing to a temp file.
func (inv *Inventory) Bytes() ([]byte, error) {
	data, err := yaml.Marshal(inv)
	if err != nil {
		return nil, err
	}
	header := "# GENERATED by `make conformance-gen` from the vendored upstream sources — do not edit.\n"
	return append([]byte(header), data...), nil
}

// Write writes the inventory to a YAML file with a GENERATED header comment.
func (inv *Inventory) Write(path string) error {
	data, err := inv.Bytes()
	if err != nil {
		return err
	}
	return os.WriteFile(path, data, 0o644)
}

// Read reads an inventory from a YAML file.
func Read(path string) (*Inventory, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var inv Inventory
	if err := yaml.Unmarshal(data, &inv); err != nil {
		return nil, fmt.Errorf("%s: %w", path, err)
	}
	return &inv, nil
}
