package inventory

import (
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strings"
	"testing"
)

func TestExtract_FixtureRoundTrip(t *testing.T) {
	inv, err := Extract(Dirs{VL: "testdata/mini-vl", VT: "testdata/mini-vt", VLVersion: "x", VTVersion: "y"})
	if err != nil {
		t.Fatal(err)
	}
	if !has(inv.Items, "route", "/select/logsql/query") || !has(inv.Items, "pipe", "coalesce") || !has(inv.Items, "traceql", "rate") || !has(inv.Items, "flag", "search.maxQueueDuration") {
		t.Fatalf("inventory incomplete: %+v", inv.Items)
	}
	p := filepath.Join(t.TempDir(), "inv.yaml")
	if err := inv.Write(p); err != nil {
		t.Fatal(err)
	}
	back, err := Read(p)
	if err != nil || len(back.Items) != len(inv.Items) || back.VLVersion != "x" {
		t.Fatalf("round trip: %v %+v", err, back)
	}
}

// TestInventory_BytesMatchesWrite proves Bytes() renders exactly what Write
// persists (header + YAML), so confgen can compare in memory instead of
// round-tripping through a temp file.
func TestInventory_BytesMatchesWrite(t *testing.T) {
	inv, err := Extract(Dirs{VL: "testdata/mini-vl", VT: "testdata/mini-vt", VLVersion: "x", VTVersion: "y"})
	if err != nil {
		t.Fatal(err)
	}
	want, err := inv.Bytes()
	if err != nil {
		t.Fatal(err)
	}
	p := filepath.Join(t.TempDir(), "inv.yaml")
	if err := inv.Write(p); err != nil {
		t.Fatal(err)
	}
	got, err := os.ReadFile(p)
	if err != nil {
		t.Fatal(err)
	}
	if string(got) != string(want) {
		t.Fatalf("Bytes() does not match what Write persisted:\nBytes: %s\nWrite: %s", want, got)
	}
	if !strings.HasPrefix(string(want), "# GENERATED by") {
		t.Fatalf("Bytes() missing GENERATED header: %s", want)
	}
}

// Real vendored trees: required in CI (CONFORMANCE_REQUIRE_DEPS=1), optional locally.
func TestExtract_RealDeps(t *testing.T) {
	root, err := RepoRoot()
	if err != nil {
		t.Fatal(err)
	}
	d := DefaultDirs(root)
	for _, dir := range []string{d.VL, d.VT} {
		if _, err := os.Stat(dir); err != nil {
			if os.Getenv("CONFORMANCE_REQUIRE_DEPS") == "1" {
				t.Fatalf("deps missing (%s): run make deps-logs deps-traces deps-vt", dir)
			}
			t.Skip("vendored deps not present locally")
		}
	}
	inv, err := Extract(d)
	if err != nil {
		t.Fatal(err)
	}
	for _, w := range [][2]string{{"route", "/select/logsql/query"}, {"route", "/select/jaeger/api/traces/"}, {"route", "/select/tempo/api/search"},
		{"pipe", "stats"}, {"filter", "range"}, {"stats", "quantile"}, {"traceql", "histogram_over_time"}, {"flag", "search.maxConcurrentRequests"}} {
		if !has(inv.Items, w[0], w[1]) {
			t.Fatalf("real deps: missing %v", w)
		}
	}
	if d.VLVersion == "" || d.VTVersion == "" {
		t.Fatalf("versions not read from Makefile: %+v", d)
	}

	// TraceQL metric-pipe functions: assert the exact expected set (not
	// just a few sampled names) against the real vendored pipe_metrics.go,
	// so a regression in the isKeyword-derivation (extract_engine.go) that
	// drops or spuriously adds a function is caught here even if the
	// hand-written mini-vt fixture test still passes.
	var traceqlNames []string
	for _, it := range inv.Items {
		if it.Kind == "traceql" {
			traceqlNames = append(traceqlNames, it.Name)
		}
	}
	sort.Strings(traceqlNames)
	wantTraceQL := []string{
		"avg_over_time", "compare", "count_over_time", "histogram_over_time",
		"max_over_time", "min_over_time", "quantile_over_time", "rate", "sum_over_time",
	}
	if !reflect.DeepEqual(traceqlNames, wantTraceQL) {
		t.Fatalf("real deps: TraceQL function set = %v, want exactly %v", traceqlNames, wantTraceQL)
	}

	// Log counts per kind for transparency
	counts := make(map[string]int)
	for _, it := range inv.Items {
		counts[it.Kind]++
	}
	t.Logf("real deps inventory: routes=%d pipes=%d filters=%d stats=%d traceql=%d flags=%d total=%d",
		counts["route"], counts["pipe"], counts["filter"], counts["stats"], counts["traceql"], counts["flag"], len(inv.Items))
}

// TestVLSurface_TracesPinEqualsLogsPin guards the claim in DefaultDirs' doc
// comment: the traces module vendors its own separate copy of VictoriaLogs
// (pinned to VL_COMMIT_TRACES), and DefaultDirs only extracts the logs-pin
// copy (deps/VictoriaLogs) for the shared VL surface (routes, engine tables,
// flags). This test proves that shortcut is safe by extracting the same
// surface from both copies and asserting item-for-item equality. If the two
// pins ever diverge, this test fails and DefaultDirs must extract both.
func TestVLSurface_TracesPinEqualsLogsPin(t *testing.T) {
	root, err := RepoRoot()
	if err != nil {
		t.Fatal(err)
	}
	d := DefaultDirs(root)
	tracesVL := filepath.Join(root, "lakehouse-traces", "deps", "VictoriaLogs")
	for _, dir := range []string{d.VL, tracesVL} {
		if _, err := os.Stat(dir); err != nil {
			if os.Getenv("CONFORMANCE_REQUIRE_DEPS") == "1" {
				t.Fatalf("deps missing (%s): run make deps-logs deps-traces", dir)
			}
			t.Skip("vendored deps not present locally")
		}
	}

	logsRoutes, err := ExtractVLRoutes(d.VL)
	if err != nil {
		t.Fatal(err)
	}
	tracesRoutes, err := ExtractVLRoutes(tracesVL)
	if err != nil {
		t.Fatal(err)
	}
	if !reflect.DeepEqual(logsRoutes, tracesRoutes) {
		t.Fatalf("VL routes differ between logs pin and traces pin:\nlogs:   %+v\ntraces: %+v", logsRoutes, tracesRoutes)
	}

	logsEngine, err := ExtractEngine(d.VL)
	if err != nil {
		t.Fatal(err)
	}
	tracesEngine, err := ExtractEngine(tracesVL)
	if err != nil {
		t.Fatal(err)
	}
	if !reflect.DeepEqual(logsEngine, tracesEngine) {
		t.Fatalf("VL engine tables differ between logs pin and traces pin:\nlogs:   %+v\ntraces: %+v", logsEngine, tracesEngine)
	}

	logsFlags, err := ExtractFlags(d.VL, VLFlagPackages, LinkedIntoLH, "vl")
	if err != nil {
		t.Fatal(err)
	}
	tracesFlags, err := ExtractFlags(tracesVL, VLFlagPackages, LinkedIntoLH, "vl")
	if err != nil {
		t.Fatal(err)
	}
	if !reflect.DeepEqual(logsFlags, tracesFlags) {
		t.Fatalf("VL flags differ between logs pin and traces pin:\nlogs:   %+v\ntraces: %+v", logsFlags, tracesFlags)
	}
}

// TestInventory_FullRoundTripEquality proves Write→Read reproduces the
// exact same Inventory struct, field for field (not just item count and one
// version field, which TestExtract_FixtureRoundTrip already checked) —
// including per-item Surface, Linked, and the VLCommitTraces pin.
func TestInventory_FullRoundTripEquality(t *testing.T) {
	inv, err := Extract(Dirs{VL: "testdata/mini-vl", VT: "testdata/mini-vt", VLVersion: "x", VTVersion: "y", VLCommitTraces: "deadbeef"})
	if err != nil {
		t.Fatal(err)
	}
	if len(inv.Items) == 0 {
		t.Fatal("fixture extraction produced no items — test would pass vacuously")
	}
	p := filepath.Join(t.TempDir(), "inv.yaml")
	if err := inv.Write(p); err != nil {
		t.Fatal(err)
	}
	back, err := Read(p)
	if err != nil {
		t.Fatal(err)
	}
	if !reflect.DeepEqual(inv, back) {
		t.Fatalf("round trip is not field-for-field equal:\nwant: %+v\ngot:  %+v", inv, back)
	}
}

// TestInventory_Write_ErrorOnBadPath proves Write surfaces the underlying
// os.WriteFile error (e.g. a parent directory that does not exist) instead
// of silently discarding it.
func TestInventory_Write_ErrorOnBadPath(t *testing.T) {
	inv := &Inventory{VLVersion: "x", VTVersion: "y"}
	err := inv.Write(filepath.Join(t.TempDir(), "no-such-dir", "inv.yaml"))
	if err == nil {
		t.Fatal("expected an error writing into a nonexistent directory")
	}
}

// TestInventory_Read_MissingFile proves Read surfaces the os.ReadFile error
// for a missing file rather than returning a zero-value Inventory silently.
func TestInventory_Read_MissingFile(t *testing.T) {
	_, err := Read(filepath.Join(t.TempDir(), "does-not-exist.yaml"))
	if err == nil {
		t.Fatal("expected an error reading a missing file")
	}
}

// TestInventory_Read_MalformedYAML proves Read wraps a YAML decode error
// with the file path (fmt.Errorf("%s: %w", path, err)), so the error
// message tells you which file failed to parse.
func TestInventory_Read_MalformedYAML(t *testing.T) {
	p := filepath.Join(t.TempDir(), "bad.yaml")
	if err := os.WriteFile(p, []byte("items: [this is not, valid: yaml: at all"), 0o644); err != nil {
		t.Fatal(err)
	}
	_, err := Read(p)
	if err == nil {
		t.Fatal("expected a YAML decode error")
	}
	if !strings.Contains(err.Error(), p) {
		t.Fatalf("expected the error to mention the file path %q, got: %v", p, err)
	}
}
