// Package report renders the generated conformance documents.
package report

import (
	"fmt"
	"sort"
	"strings"

	"github.com/ReliablyObserve/victoria-lakehouse/tests/conformance/inventory"
	"github.com/ReliablyObserve/victoria-lakehouse/tests/conformance/registry"
)

func icon(r *registry.Row) string {
	switch {
	case r == nil:
		return "⚪ no row"
	case r.Expect == registry.ExpectAbsent:
		return "⛔ absent upstream and on LH"
	case r.Expect == registry.ExpectUnsupported:
		return "⛔ unsupported on cold (documented)"
	case r.Expect == registry.ExpectDiffer:
		return "🔁 differs: " + r.DifferNote
	case r.Pending:
		return "🟡 declared, not yet executed"
	case r.Origin == registry.OriginLHAddition:
		return "🧩 LH addition"
	default:
		return "✅ native, verified"
	}
}

// RenderCoverage produces UPSTREAM_COVERAGE.md: every upstream item with its
// covering row and status, then every LH addition.
func RenderCoverage(inv *inventory.Inventory, reg *registry.Registry) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# Upstream API coverage (GENERATED by `make conformance-gen` — do not edit)\n\n")
	if inv.VLCommitTraces != "" {
		fmt.Fprintf(&b, "Upstream: VictoriaLogs %s (traces module vendors its own VictoriaLogs copy pinned at commit %s) · VictoriaTraces %s. Source of truth: `tests/conformance/registry/rows/` + `tests/conformance/inventory.generated.yaml`.\n\n", inv.VLVersion, inv.VLCommitTraces, inv.VTVersion)
	} else {
		fmt.Fprintf(&b, "Upstream: VictoriaLogs %s · VictoriaTraces %s. Source of truth: `tests/conformance/registry/rows/` + `tests/conformance/inventory.generated.yaml`.\n\n", inv.VLVersion, inv.VTVersion)
	}
	keys := reg.UpstreamKeys()
	byKind := map[string][]inventory.Item{}
	for _, it := range inv.Items {
		byKind[it.Kind] = append(byKind[it.Kind], it)
	}
	for _, kind := range []string{"route", "pipe", "filter", "stats", "traceql", "flag"} {
		items := byKind[kind]
		if len(items) == 0 {
			continue
		}
		sort.Slice(items, func(i, j int) bool { return items[i].Name < items[j].Name })
		fmt.Fprintf(&b, "## Upstream %s (%d)\n\n| %s | Source | Rows | Status |\n|---|---|---|---|\n", kind, len(items), kind)
		for _, it := range items {
			ids := keys[inv.Key(it)]
			var first *registry.Row
			if len(ids) > 0 {
				first = reg.ByID[ids[0]]
			}
			status := icon(first)
			if kind == "flag" && !it.Linked {
				status += " (package not linked into LH)"
				if first == nil {
					status = "⚪ not linked into LH, no row"
				}
			}
			fmt.Fprintf(&b, "| `%s` | `%s` | %s | %s |\n", it.Name, it.Source, strings.Join(ids, ", "), status)
		}
		b.WriteString("\n")
	}
	fmt.Fprintf(&b, "## Lakehouse additions (no upstream equivalent)\n\n| Row | Title | Kind | Status |\n|---|---|---|---|\n")
	for _, r := range reg.Rows {
		if r.Origin == registry.OriginLHAddition {
			fmt.Fprintf(&b, "| `%s` | %s | %s | %s |\n", r.ID, r.Title, r.Kind, icon(&r))
		}
	}
	return b.String()
}
