package report

import (
	"fmt"
	"sort"
	"strings"

	"github.com/ReliablyObserve/victoria-lakehouse/tests/conformance/registry"
)

// README markers delimiting the generated "Key Features" bullets. Everything
// between them is regenerated from the feature catalog; the surrounding
// README structure (the heading, the section order, the prose around it) is
// hand-written and left alone.
const (
	ReadmeFeaturesBegin = "<!-- features:begin -->"
	ReadmeFeaturesEnd   = "<!-- features:end -->"
)

// Status icons for a catalog feature. The distinction that matters is
// IconShipped vs IconDeclared: both are shipped code, but only the first has
// verification that actually runs today.
const (
	IconShipped    = "✅" // shipped and verified: >= 1 executing test or >= 1 non-pending registry row
	IconDeclared   = "🟡" // shipped, but every registry row is still pending and no test is linked
	IconInProgress = "🔧"
	IconPlanned    = "📝"
)

// FeatureStatus is one feature with its verification resolved against the
// registry: which rows it cites, whether any of them actually executes, and
// the icon the generated documents show for it.
type FeatureStatus struct {
	Feature  *registry.Feature
	Rows     []*registry.Row // rows cited by the feature, in citation order (missing ids are dropped)
	Missing  []string        // cited row ids the registry does not have
	Icon     string
	Verified bool // has an executing verification: a linked test, or a non-pending row
}

// StatusOf resolves one feature's rows and verification state.
func StatusOf(f *registry.Feature, reg *registry.Registry) FeatureStatus {
	st := FeatureStatus{Feature: f}
	executing := len(f.Tests) > 0
	for _, id := range f.Rows {
		r := reg.ByID[id]
		if r == nil {
			st.Missing = append(st.Missing, id)
			continue
		}
		st.Rows = append(st.Rows, r)
		if !r.Pending {
			executing = true
		}
	}
	st.Verified = executing
	switch {
	case f.Status == registry.StatusPlanned:
		st.Icon = IconPlanned
	case f.Status == registry.StatusInProgress:
		st.Icon = IconInProgress
	case executing:
		st.Icon = IconShipped
	default:
		st.Icon = IconDeclared
	}
	return st
}

// Statuses resolves every feature of the catalog, in catalog report order.
func Statuses(set *registry.FeatureSet, reg *registry.Registry) []FeatureStatus {
	out := make([]FeatureStatus, 0, len(set.Features))
	for i := range set.Features {
		out = append(out, StatusOf(&set.Features[i], reg))
	}
	return out
}

// VerificationGaps returns the ids of shipped features with no executing
// verification (icon 🟡) — the list a maintainer works down: shipped code
// whose only claim of correctness is a declared, not-yet-executed row.
func VerificationGaps(set *registry.FeatureSet, reg *registry.Registry) []string {
	var out []string
	for _, st := range Statuses(set, reg) {
		if st.Feature.Status == registry.StatusShipped && !st.Verified {
			out = append(out, st.Feature.ID)
		}
	}
	sort.Strings(out)
	return out
}

// areaTitle renders an area name as a document heading ("ui" -> "UI").
func areaTitle(a registry.Area) string {
	switch a {
	case "ui":
		return "UI"
	case "ops":
		return "Ops"
	default:
		return strings.ToUpper(string(a[:1])) + string(a[1:])
	}
}

// rowSummary renders one cited row for the verification line: its id plus
// the expectation it declares and whether it executes yet.
func rowSummary(r *registry.Row) string {
	state := "executes"
	if r.Pending {
		state = "pending"
	}
	return fmt.Sprintf("`%s` (%s, %s)", r.ID, r.Expect, state)
}

// codeList renders a list of references as inline-code, comma separated.
func codeList(items []string) string {
	out := make([]string, 0, len(items))
	for _, it := range items {
		out = append(out, "`"+it+"`")
	}
	return strings.Join(out, ", ")
}

// RenderFeatures produces docs/features.md: a summary table, the
// verification-gap list, then every feature grouped by area.
func RenderFeatures(set *registry.FeatureSet, reg *registry.Registry) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# Lakehouse features (GENERATED by `make conformance-gen` — do not edit)\n\n")
	fmt.Fprintf(&b, "Every Lakehouse capability, where it is verified, and where it is documented. Source of truth: `tests/conformance/registry/features/`. The same catalog generates the \"Key Features\" bullets in `README.md`; the conformance gate fails a PR whose `### Added` changelog bullet, new route, flag or handler is not represented here — see `tests/conformance/README.md`.\n\n")
	fmt.Fprintf(&b, "Legend: %s shipped, with verification that executes today (a linked test, or a registry row that is not `pending`) · %s shipped, declared only — every linked row is still `pending` and no test is linked · %s in progress · %s planned (documented, not implemented)\n\n",
		IconShipped, IconDeclared, IconInProgress, IconPlanned)

	statuses := Statuses(set, reg)

	// Summary table: features per area x status.
	fmt.Fprintf(&b, "## Summary\n\n| Area | %s verified | %s declared only | %s in progress | %s planned | Total |\n|---|---|---|---|---|---|\n",
		IconShipped, IconDeclared, IconInProgress, IconPlanned)
	type counts struct{ verified, declared, inProgress, planned int }
	perArea := map[registry.Area]*counts{}
	total := counts{}
	for _, st := range statuses {
		c := perArea[st.Feature.Area]
		if c == nil {
			c = &counts{}
			perArea[st.Feature.Area] = c
		}
		switch st.Icon {
		case IconShipped:
			c.verified++
			total.verified++
		case IconDeclared:
			c.declared++
			total.declared++
		case IconInProgress:
			c.inProgress++
			total.inProgress++
		default:
			c.planned++
			total.planned++
		}
	}
	for _, area := range registry.Areas {
		c := perArea[area]
		if c == nil {
			continue
		}
		n := c.verified + c.declared + c.inProgress + c.planned
		fmt.Fprintf(&b, "| %s | %d | %d | %d | %d | %d |\n", areaTitle(area), c.verified, c.declared, c.inProgress, c.planned, n)
	}
	n := total.verified + total.declared + total.inProgress + total.planned
	fmt.Fprintf(&b, "| **Total** | **%d** | **%d** | **%d** | **%d** | **%d** |\n\n", total.verified, total.declared, total.inProgress, total.planned, n)

	// Verification gaps.
	fmt.Fprintf(&b, "## Verification gaps\n\nShipped features whose only verification is a declared, not-yet-executed registry row. Closing a gap means linking a real test in the feature's `tests:`.\n\n")
	gaps := 0
	for _, st := range statuses {
		if st.Feature.Status != registry.StatusShipped || st.Verified {
			continue
		}
		gaps++
		fmt.Fprintf(&b, "- `%s` — %s (%s)\n", st.Feature.ID, st.Feature.Title, areaTitle(st.Feature.Area))
	}
	if gaps == 0 {
		fmt.Fprintf(&b, "None: every shipped feature has at least one executing test or non-pending registry row.\n")
	}
	b.WriteString("\n")

	for _, area := range registry.Areas {
		features := set.ByArea(area)
		if len(features) == 0 {
			continue
		}
		fmt.Fprintf(&b, "## %s (%d)\n\n", areaTitle(area), len(features))
		for _, f := range features {
			st := StatusOf(f, reg)
			fmt.Fprintf(&b, "### %s %s\n\n", st.Icon, f.Title)
			since := f.Since
			if since == registry.SinceUnreleased {
				since = "unreleased"
			}
			surfaces := make([]string, 0, len(f.Surfaces))
			for _, s := range f.Surfaces {
				surfaces = append(surfaces, string(s))
			}
			fmt.Fprintf(&b, "`%s` · status: %s · since: %s · surfaces: %s\n\n", f.ID, f.Status, since, strings.Join(surfaces, ", "))
			fmt.Fprintf(&b, "%s\n\n", strings.TrimSpace(f.Highlight))
			fmt.Fprintf(&b, "%s\n\n", strings.TrimSpace(f.Description))

			var verification []string
			if len(st.Rows) > 0 {
				parts := make([]string, 0, len(st.Rows))
				for _, r := range st.Rows {
					parts = append(parts, rowSummary(r))
				}
				verification = append(verification, "rows: "+strings.Join(parts, ", "))
			}
			if len(f.Tests) > 0 {
				verification = append(verification, "tests: "+codeList(f.Tests))
			}
			if len(f.Bench) > 0 {
				verification = append(verification, "bench: "+codeList(f.Bench))
			}
			if len(verification) == 0 {
				verification = append(verification, "none linked yet")
			}
			fmt.Fprintf(&b, "- Verification: %s\n", strings.Join(verification, " · "))
			if len(f.Docs) > 0 {
				fmt.Fprintf(&b, "- Docs: %s\n", codeList(f.Docs))
			}
			if len(f.Changelog) > 0 {
				fmt.Fprintf(&b, "- Changelog: %s\n", codeList(f.Changelog))
			}
			if strings.TrimSpace(f.Notes) != "" {
				fmt.Fprintf(&b, "- Note: %s\n", strings.TrimSpace(f.Notes))
			}
			b.WriteString("\n")
		}
	}

	return b.String()
}

// RenderReadmeFeatures produces the generated body of README.md's "Key
// Features" block: the highlight of every feature that names a
// `readme_section`, grouped by those sections in README order. Planned and
// in-progress features are marked inline so the README never claims
// something ships before it does.
func RenderReadmeFeatures(set *registry.FeatureSet) string {
	bySection := map[string][]*registry.Feature{}
	for i := range set.Features {
		f := &set.Features[i]
		if f.ReadmeSection == "" {
			continue
		}
		bySection[f.ReadmeSection] = append(bySection[f.ReadmeSection], f)
	}

	var b strings.Builder
	for _, section := range registry.ReadmeSections {
		features := bySection[section]
		if len(features) == 0 {
			continue
		}
		sort.SliceStable(features, func(i, j int) bool { return features[i].ID < features[j].ID })
		fmt.Fprintf(&b, "### %s\n", section)
		for _, f := range features {
			prefix := ""
			switch f.Status {
			case registry.StatusInProgress:
				prefix = IconInProgress + " *(in progress)* "
			case registry.StatusPlanned:
				prefix = IconPlanned + " *(planned)* "
			}
			fmt.Fprintf(&b, "- %s%s\n", prefix, strings.TrimSpace(f.Highlight))
		}
		b.WriteString("\n")
	}
	return strings.TrimRight(b.String(), "\n") + "\n"
}

// ReplaceMarkedBlock returns doc with the text between the begin and end
// markers replaced by block (the markers themselves are kept). It fails
// loudly when a marker is missing or out of order rather than appending or
// silently rewriting the whole document.
func ReplaceMarkedBlock(doc, begin, end, block string) (string, error) {
	i := strings.Index(doc, begin)
	if i < 0 {
		return "", fmt.Errorf("marker %q not found", begin)
	}
	j := strings.Index(doc, end)
	if j < 0 {
		return "", fmt.Errorf("marker %q not found", end)
	}
	if j < i+len(begin) {
		return "", fmt.Errorf("marker %q appears before %q", end, begin)
	}
	return doc[:i+len(begin)] + "\n" + block + doc[j:], nil
}
